# Generated by Django 3.2.9 on 2022-01-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
